### PR TITLE
Signals: implement sigaltstack()

### LINKED ISSUE #927: implement sigaltstack
After merging #925, add support for sigaltstack(2) and SA_ONSTACK.

### LINKED ISSUE #1131: potential go 1.14 / signal issue
```
 go version
go version go1.14.1 linux/amd64
```

```
eyberg@box:~/g$ ops run -p 8080 g
booting /home/eyberg/.ops/images/g.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
signal 23 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x8a6412890
stack: frame={sp:0x830026348, fp:0x8300263a0} stack=[0x83001e278,0x830026678)
0000000830026248:  0000000830026268  0000000000449c5f <runtime.sigNotOnStack+127>
0000000830026258:  000000000070a528  0000000000000039
0000000830026268:  00000008300262c0  0000000000448c3b <runtime.adjustSignalStack+395>
0000000830026278:  0000000000000017  0000000830026290
0000000830026288:  00000008300262d0  0000000000000000
0000000830026298:  0000000000000000  0000000000000000
00000008300262a8:  0000000000000000  0000000000000000
00000008300262b8:  0000000000000000  0000000830026338
00000008300262c8:  00000000004489a0 <runtime.sigtrampgo+288>  0000000800000017
00000008300262d8:  0000000830028a80  00000008300262f8
00000008300262e8:  0000000000000000  0000000000000000
00000008300262f8:  0000000000000000  0000000000000000
0000000830026308:  0000000000000000  0000000000000000
0000000830026318:  0000000000000000  0000000830001c80
0000000830026328:  00000008300264d0  00000008300263a0
0000000830026338:  0000000830026390  0000000000464bf3 <runtime.sigtramp+67>
0000000830026348: <0000000000000017  00000008300264d0
0000000830026358:  00000008300263a0  0000000000000000
0000000830026368:  0000000000000000  0000000000000000
0000000830026378:  0000000000000000  0000000830026390
0000000830026388:  0000000000000000  0000000000000000
0000000830026398: !00000008a6412890 >0000000000000000
00000008300263a8:  0000000000000000  0000000000000000
00000008300263b8:  0000000000000000  0000000000000000
00000008300263c8:  0000000000000001  0000000000000002
00000008300263d8:  0000000000000000  0000000000000206
00000008300263e8:  0000000000000000  0000000000000000
00000008300263f8:  0000000000757558  0000000000000000
0000000830026408:  0000000000000007  0000000830064eb1
0000000830026418:  0000000830026638  0000000830016000
0000000830026428:  0000000000000001  fffffffffffffff5
0000000830026438:  000000000049df9b <syscall.Syscall+27>  00000008300265e8
0000000830026448:  000000000049df9b <syscall.Syscall+27>  0000000000000212
0000000830026458:  000000000000002b  0000000000000006
0000000830026468:  0000000000000000  ffffffffffffffff
0000000830026478:  00000008e0305000  0000000000000000
0000000830026488:  0000000000000000  0000000000000000
0000000830026498:  0000000000000000
runtime.throw(0x70a528, 0x39)
        /usr/local/go/src/runtime/panic.go:1114 +0x72
runtime.sigNotOnStack(0x17)
        /usr/local/go/src/runtime/signal_unix.go:879 +0x7f
runtime.adjustSignalStack(0x800000017, 0x830028a80, 0x8300262f8, 0x0)
        /usr/local/go/src/runtime/signal_unix.go:497 +0x18b
runtime.sigtrampgo(0x17, 0x8300264d0, 0x8300263a0)
        /usr/local/go/src/runtime/signal_unix.go:440 +0x120
runtime: unexpected return pc for runtime.sigtramp called from 0x8a6412890
stack: frame={sp:0x830026348, fp:0x8300263a0} stack=[0x83001e278,0x830026678)
0000000830026248:  0000000830026268  0000000000449c5f <runtime.sigNotOnStack+127>
0000000830026258:  000000000070a528  0000000000000039
0000000830026268:  00000008300262c0  0000000000448c3b <runtime.adjustSignalStack+395>
0000000830026278:  0000000000000017  0000000830026290
0000000830026288:  00000008300262d0  0000000000000000
0000000830026298:  0000000000000000  0000000000000000
00000008300262a8:  0000000000000000  0000000000000000
00000008300262b8:  0000000000000000  0000000830026338
00000008300262c8:  00000000004489a0 <runtime.sigtrampgo+288>  0000000800000017
00000008300262d8:  0000000830028a80  00000008300262f8
00000008300262e8:  0000000000000000  0000000000000000
00000008300262f8:  0000000000000000  0000000000000000
0000000830026308:  0000000000000000  0000000000000000
0000000830026318:  0000000000000000  0000000830001c80
0000000830026328:  00000008300264d0  00000008300263a0
0000000830026338:  0000000830026390  0000000000464bf3 <runtime.sigtramp+67>
0000000830026348: <0000000000000017  00000008300264d0
0000000830026358:  00000008300263a0  0000000000000000
0000000830026368:  0000000000000000  0000000000000000
0000000830026378:  0000000000000000  0000000830026390
0000000830026388:  0000000000000000  0000000000000000
0000000830026398: !00000008a6412890 >0000000000000000
00000008300263a8:  0000000000000000  0000000000000000
00000008300263b8:  0000000000000000  0000000000000000
00000008300263c8:  0000000000000001  0000000000000002
00000008300263d8:  0000000000000000  0000000000000206
00000008300263e8:  0000000000000000  0000000000000000
00000008300263f8:  0000000000757558  0000000000000000
0000000830026408:  0000000000000007  0000000830064eb1
0000000830026418:  0000000830026638  0000000830016000
0000000830026428:  0000000000000001  fffffffffffffff5
0000000830026438:  000000000049df9b <syscall.Syscall+27>  00000008300265e8
0000000830026448:  000000000049df9b <syscall.Syscall+27>  0000000000000212
0000000830026458:  000000000000002b  0000000000000006
0000000830026468:  0000000000000000  ffffffffffffffff
0000000830026478:  00000008e0305000  0000000000000000
0000000830026488:  0000000000000000  0000000000000000
0000000830026498:  0000000000000000
runtime.sigtramp(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x2, 0x0, 0x206, 0x0, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:389 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0x830036fe8 sp=0x830036fe0 pc=0x462cf1

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x8e0304f18, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0x8300ac018, 0x72, 0x0, 0x0, 0x6fb01e)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0x8300ac000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0x8300ac000, 0x5a58f95fe6f6a301, 0x830050190, 0x5a58f95fe6f6a300)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0x83000e280, 0x5e988075, 0x830037da8, 0x4a8e76)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0x83000e280, 0x830037df8, 0x18, 0x830000180, 0x6415fc)
        /usr/local/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0x8300aa000, 0x7660c0, 0x83000e280, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2901 +0x25d
net/http.(*Server).ListenAndServe(0x8300aa000, 0x8300aa000, 0x8)
        /usr/local/go/src/net/http/server.go:2830 +0xb7
net/http.ListenAndServe(...)
        /usr/local/go/src/net/http/server.go:3086
main.main()
        /home/eyberg/g/main.go:16 +0x124
goroutine 6 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
sync.runtime_notifyListWait(0x8300443d0, 0x0)
        /usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0x8300443c0)
        /usr/local/go/src/sync/cond.go:56 +0x9d
net/http.(*connReader).abortPendingRead(0x830064ea0)
        /usr/local/go/src/net/http/server.go:726 +0xad
net/http.(*response).finishRequest(0x8300aa0e0)
        /usr/local/go/src/net/http/server.go:1596 +0x96
net/http.(*conn).serve(0x830076a00, 0x766900, 0x830044340)
        /usr/local/go/src/net/http/server.go:1900 +0x8aa
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c

goroutine 7 [syscall]:
syscall.Syscall(0x0, 0x7, 0x830064eb1, 0x1, 0x4aebb5, 0x8e0304e38, 0x72)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x7, 0x830064eb1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
        /usr/local/go/src/syscall/syscall_unix.go:189
internal/poll.(*FD).Read(0x8300ac080, 0x830064eb1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:165 +0x133
net.(*netFD).Read(0x8300ac080, 0x830064eb1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0x830010038, 0x830064eb1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
net/http.(*connReader).backgroundRead(0x830064ea0)
        /usr/local/go/src/net/http/server.go:678 +0x58
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:674 +0xd0
```

seems fine on 

```
 go version
go version go1.13.6 linux/amd64
```

```
cat main.go
package main

import (
  "fmt"
  "net/http"
)

func main() {
  http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Welcome to my website!")
  })

  fs := http.FileServer(http.Dir("static/"))
  http.Handle("/static/", http.StripPrefix("/static/", fs))

  http.ListenAndServe(":8080", nil)
}
```

### PR DESCRIPTION
**Pull request by francescolavra**
Commit 47a38f6e03ffc62b931997e1fb73f0f8eed4382c added an implementation of sigaltstack() but didn't acctually link it to the corresponding syscall number. This commit modifies the implementation to properly handle NULL arguments and invalid argument data, and links the sigaltstack() function to the syscall number; in addition, runtime tests to exercise the new code are being added.

Closes #927.
Closes #1131.

### CODE REVIEW

File: test/runtime/signal.c [hunk 1]
```diff
@@ -888,6 +888,99 @@ void test_signalfd(void)
...
+
+    ss.ss_flags = SS_DISABLE;
+    if (sigaltstack(&ss, NULL) < 0)
+        fail_perror("sigaltstack(&ss, NULL)");
+    if (sigaltstack(NULL, &oss) < 0)
+        fail_perror("sigaltstack(NULL, &oss)");
+    if (!(oss.ss_flags & SS_DISABLE))
+        fail_error("oss.ss_flags 0x%x\n", oss.ss_flags);
+
+    ss.ss_flags = ~0 & ~SS_DISABLE;
```
Comment (wjhun) [inline test/runtime/signal.c:970]: What is the purpose of "~0 &" here?

Comment (francescolavra) [reply test/runtime/signal.c]: Oops, it's a leftover that I forgot to remove. Fixed.
