### PR TITLE
x86 init_cpu_features(): enable SSE state in XCR0 when using XSAVE

### LINKED ISSUE #1528: exit status 255
I'm doing test run in ubuntu 20.04 running inside vmware and host as win10. It's giving me error for following command

`ops pkg load node_v14.2.0 -p 8081 -f -n -a exp.js`

```
Process abort: Unhandled SIGSEGV received by thread 6

 interrupt: 00000000000000ea
     frame: ffff800001c03c00

   rax: 0000000000000000
   rbx: 000000000000000b
   rcx: 0000000000000000
   rdx: 000000000000000b
   rsi: 0000000000000006
   rdi: 0000000000000002
   rbp: 00000001072ba8f0
   rsp: 00000001072ba710
    r8: 000000000000000b
    r9: 00000001072ba710
   r10: 0000000000000008
   r11: 0000000000000000
   r12: 0000000000000000
   r13: 0000000000000000
   r14: 0000000000000000
   r15: 0000000000000000
   rip: 0000022bcff34705
rflags: 0000000000000246
    ss: 0000000000000000
    cs: 000000000000002b
    ds: 0000000000000000
    es: 0000000000000000
fsbase: 00000001072bb700
gsbase: 0000000000000000

frame trace:
00000001072ba8f8:   0000022bcff34890

stack trace:
00000001072ba710:   0000000000000600
00000001072ba720:   0000000000000000
00000001072ba730:   0000000000000000
00000001072ba740:   0000000000000000
00000001072ba750:   0000000000000000
00000001072ba760:   0000000000000000
00000001072ba770:   0000000000000000
00000001072ba780:   0000000000000000
00000001072ba790:   fffffffe7fffffff
00000001072ba7a0:   ffffffffffffffff
00000001072ba7b0:   ffffffffffffffff
00000001072ba7c0:   ffffffffffffffff
00000001072ba7d0:   ffffffffffffffff
00000001072ba7e0:   ffffffffffffffff
00000001072ba7f0:   ffffffffffffffff
00000001072ba800:   ffffffffffffffff

Terminating.
exit status 255

```

### PR DESCRIPTION
**Pull request by francescolavra**
The FXSAVE and FXRSTOR instructions manage both the x87 state and the SSE state; in order to provide equivalent functionality when using XSAVE/XRSTOR, bit 1 of XCR0 must be set to 1, otherwise the SSE state is not managed.
As noted in the Intel Architecture SDM (volume 1, chapter 13 "Managing state using the xsave feature set", section 13.2 "Enabling the xsave feature set and xsave-enabled features"), every processor that supports the XSAVE feature set allows software to set XCR0[1].
This fixes unwanted SEGV signals being triggered by multi-threaded programs using SSE instructions on CPUs that support the xsave features but not the AVX instructions.
Example output when running `ops pkg load node_v14.2.0 -a hi.js`:
```
en1: assigned 10.0.2.15
en1: assigned FE80::CCDC:27FF:FEF2:9DB3
signal 11 received by tid 1, errno 0, code 1
   fault address 0x40008
   core dump (unimplemented)
```

Closes #1528.

### CODE REVIEW

**Comment by sanderssj** [comment]
LGTM!

File: src/x86_64/mp.c [hunk 1]
```diff
@@ -48,11 +48,11 @@ void init_cpu_features()
     cr &= ~C0_EM;
     mov_to_cr("cr0", cr);
     if (use_xsave) {
-        if (v[2] & CPUID_AVX) {
-            xgetbv(0, &v[0], &v[1]);
-            v[0] |= XCR0_SSE | XCR0_AVX;
-            xsetbv(0, v[0], v[1]);
-        }
+        xgetbv(0, &v[0], &v[1]);
+        v[0] |= XCR0_SSE;
```
Comment (sanderssj) [inline src/x86_64/mp.c:52]: Have you found something that says the presence of xsave implies the presence of sse? I think that's true, but I haven't found documentation to confirm yet.

Comment (francescolavra) [reply src/x86_64/mp.c:52]: The Intel SDM (vol. 1, section 13.2, CPUID function 0DH, sub-function 0) says that the presence of xsave guarantees that the SSE state can be managed by xsave/xrstor. I think this implies that SSE instructions are supported, since it would make little sense to save/restore the SSE state if this state cannot be used by software. But I didn't find any explicit sentence that says that every cpu that supports xsave must also support SSE instructions.

**Review by wjhun — APPROVED** [review]
